### Recover all the movies
GET http://localhost:1234/movies

### Recover one movie by id
Get http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recover all the movies by genre
Get http://localhost:1234/movies?genre=action


### Create a movie
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql":"Select * from users",
  "title": "The Shawshank Redemption",
  "year": 1994,
  "director": "Frank Darabont",
  "duration": 142,
  "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
  "genre": [
    "Drama"
  ]
}

### Delete a movie
DELETE http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Update a movie
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2016
}